import = [
   "~/.config/alacritty/catppuccin-macchiato.toml"
]

[font]

normal.family = "FiraCode Nerd Font"
bold.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font"
bold_italic.family = "FiraCode Nerd Font"

size = 19.0

[window]

startup_mode = "Fullscreen"
